# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_postmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
